language: java
jdk: oraclejdk8

branches:
  only:
  - master

install: mvn package --batch-mode --show-version --settings .travis.settings.xml

notifications:
  email:
    on_success: never
    on_failure: always
